services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres_data: