# fly.toml app configuration file generated on 2024-08-03T22:14:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$APP_NAME'
primary_region = '$PRIMARY_REGION'

[build]

[env]
  PORT = '8000'
  BASE_URL = '$BASE_URL'
  ZUPASS_URL = '$ZUPASS_URL'

[processes]
  app = 'task api:start'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v1/conferences"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
