export const adjectives = [
  "snarky",
  "lazy",
  "brave",
  "swift",
  "gentle",
  "mighty",
  "wise",
  "fierce",
  "loyal",
  "cunning",
  "radiant",
  "bold",
  "resolute",
  "silent",
  "stealthy",
  "fearless",
  "tenacious",
  "elegant",
  "playful",
  "crafty",
  "daring",
  "graceful",
  "curious",
  "serene",
  "mysterious",
  "fiery",
  "whimsical",
  "diligent",
  "vibrant",
  "spirited",
  "sneaky",
  "clever",
  "witty",
  "noble",
  "valiant",
  "jolly",
  "gritty",
  "roaring",
  "gallant",
  "zesty",
  "stormy",
  "eager",
  "proud",
  "fearsome",
  "breezy",
  "patient",
  "hasty",
  "zany",
  "reckless",
  "radiant",
  "boisterous",
];

export const animals = [
  "asian elephant",
  "indochinese tiger",
  "clouded leopard",
  "sun bear",
  "gaur",
  "banteng",
  "siamese crocodile",
  "king cobra",
  "asian water monitor",
  "asian black bear",
  "dholes (asian wild dogs)",
  "irrawaddy dolphin",
  "binturong",
  "slow loris",
  "malayan tapir",
  "gibbon",
  "serow",
  "sambar deer",
  "barking deer",
  "long-tailed macaque",
  "pig-tailed macaque",
  "crab-eating macaque",
  "asiatic jackal",
  "white-handed gibbon",
  "silvered langur",
  "dusky leaf monkey",
  "pangolin",
  "asian palm civet",
  "smooth-coated otter",
  "green peafowl",
  "asian small-clawed otter",
  "stork-billed kingfisher",
  "oriental pied hornbill",
  "great hornbill",
  "giant squirrel",
  "pied harrier",
  "asian fairy-bluebird",
  "sarus crane",
  "black-headed ibis",
  "painted stork",
  "otter civet",
  "red muntjac",
  "porcupine",
  "python",
  "rhesus macaque",
  "saltwater crocodile",
  "smooth-scaled gecko",
  "white-rumped shama",
  "malayan sun bear",
  "lesser mouse-deer",
];
