#!/bin/sh

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|json|md)$')

if [ -n "$STAGED_FILES" ]; then
  # Run deno fmt
  deno fmt $STAGED_FILES

  # Add formatted files back to staging area
  git add $STAGED_FILES
fi

exit 0
